version: '3'
services:
  dortislem:
    build: ./dortislem
    ports:
      - "3001:3001"
  
  istatistik:
    build: ./istatistik
    ports:
      - "3002:3002"
  
  birimdonusum:
    build: ./birimdonusum
    ports:
      - "3003:3003"
  
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - dortislem
      - istatistik
      - birimdonusum